---
# handlers file for ansible-kibana

- name: stop kibana
  become: true
  systemd:
    name: "{{instance_init_script | basename}}"
    state: stopped
    enabled: true
  register: stopped

- name: reload systemd configuration
  become: true
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled
- name: restart kibana
  become: true
  systemd:
    name: "{{instance_init_script | basename}}"
    state: restarted
    enabled: true
  register: started
